name: 'stock_evaluation'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'stock_evaluation'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
# analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
# macro-paths: ["macros"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

seeds:
  +schema: seed_data
models:
  stock_evaluation:
    # Config indicated by + and applies to all files under models/example/
    staging:
      schema: staging
      +materialized: view
    intermediate:
      schema: intermediate
      +materialized: view
    marts:
      schema: marts
      +materialized: view