version: 2

models:
  - name: int_already_scraped_symbols
    description: Intermediate model for already scraped stock symbols
    columns:
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - unique
          - not_null
