version: 2

models:
  - name: company_evaluation
    description: Comprehensive evaluation of companies including financial ratios, multiples, trends, and DCF evaluations
    columns:
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - unique
          - not_null
      - name: company_name
        description: Name of the company
      - name: industry
        description: Industry of the company
      - name: sector
        description: Sector of the company
      - name: current_price
        description: Current stock price
      - name: market_cap
        description: Market capitalization of the company
      - name: shares_outstanding
        description: Number of outstanding shares
      - name: earnings_per_share
        description: Earnings per share
      - name: price_earnings_ratio
        description: Price to earnings ratio
      - name: country
        description: Country of the company
      - name: comparative_ratios_score
        description: Score based on comparative financial ratios
      - name: comparative_multiples_score
        description: Score based on comparative market multiples
      - name: comparative_trends_score
        description: Score based on comparative financial trends
      - name: comparative_guideline_score
        description: Score based on comparative guideline evaluation
      - name: guideline_total_score
        description: Total score from guideline evaluation
      - name: dcf_normal_evaluation
        description: DCF evaluation under normal scenario
      - name: dcf_stable_evaluation
        description: DCF evaluation under stable scenario
      - name: dcf_stable_and_strong_growth_evaluation
        description: DCF evaluation under stable and strong growth scenario
      - name: dcf_volatile_evaluation
        description: DCF evaluation under volatile scenario
      - name: dcf_volatile_and_weak_growth_evaluation
        description: DCF evaluation under volatile and weak growth scenario
      - name: total_score
        description: Total evaluation score

  - name: dcf_model_base_data
    description: Base data for DCF model calculations
    columns:
      - name: id
        description: Unique identifier
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - not_null
      - name: shares_outstanding
        description: Number of outstanding shares
      - name: revenue_growth
        description: Average revenue growth
      - name: free_cash_flow
        description: Average free cash flow

  - name: remaining_tickers_for_alphavantage_scraper
    description: List of tickers remaining to be scraped from AlphaVantage API
    columns:
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - unique
          - not_null

  - name: remaining_tickers_for_yahoo_scraper
    description: List of tickers remaining to be scraped from Yahoo Finance API
    columns:
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - unique
          - not_null

  - name: remaining_tickers_for_fmp_scraper
    description: List of tickers remaining to be scraped from Financial Modeling Prep API
    columns:
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - unique
          - not_null
