version: 2

models:
  - name: int_fmp_combined_filings
    description: Intermediate model for combined FMP financial filings
    columns:
      - name: filing_id
        description: Unique identifier for the filing
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - not_null
      - name: end_of_period
        description: End date of the financial period
        data_tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the period
      - name: net_income
        description: Net income for the period
      - name: cost_of_goods_sold
        description: Cost of goods sold
      - name: selling_general_and_administration
        description: Selling, general, and administrative expenses
      - name: free_cash_flow
        description: Free cash flow
      - name: dividends_paid
        description: Dividends paid
      - name: stockholders_equity
        description: Stockholders' equity
      - name: total_assets
        description: Total assets
      - name: accounts_receivable
        description: Accounts receivable
      - name: cash_and_cash_equivalents
        description: Cash and cash equivalents
      - name: current_assets
        description: Current assets
      - name: current_liabilities
        description: Current liabilities
      - name: inventory
        description: Inventory
      - name: long_term_debt
        description: Long-term debt
      - name: revenue_growth
        description: Revenue growth rate

  - name: int_yahoo_filings_annually
    description: Intermediate model for combined Yahoo annual financial filings
    columns:
      - name: filing_id
        description: Unique identifier for the filing
        data_tests:
          # - unique (they dont have to be unique. there are rare occasion where two filings occur in one year, which results in the same id)
          - not_null
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - not_null
      - name: end_of_period
        description: End date of the financial period
        data_tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the period
      - name: net_income
        description: Net income for the period
      - name: cost_of_goods_sold
        description: Cost of goods sold
      - name: selling_general_and_administration
        description: Selling, general, and administrative expenses
      - name: free_cash_flow
        description: Free cash flow
      - name: dividends_paid
        description: Dividends paid
      - name: stockholders_equity
        description: Stockholders' equity
      - name: total_assets
        description: Total assets
      - name: accounts_receivable
        description: Accounts receivable
      - name: cash_and_cash_equivalents
        description: Cash and cash equivalents
      - name: current_assets
        description: Current assets
      - name: current_liabilities
        description: Current liabilities
      - name: inventory
        description: Inventory
      - name: long_term_debt
        description: Long-term debt
      - name: revenue_growth
        description: Revenue growth rate

  - name: int_alphavantage_combined_filings
    description: Intermediate model for combined Alphavantage annual financial filings
    columns:
      - name: filing_id
        description: Unique identifier for the filing
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: Stock ticker symbol
        data_tests:
          - not_null
      - name: end_of_period
        description: End date of the financial period
        data_tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the period
      - name: net_income
        description: Net income for the period
      - name: cost_of_goods_sold
        description: Cost of goods sold
      - name: selling_general_and_administration
        description: Selling, general, and administrative expenses
      - name: free_cash_flow
        description: Free cash flow
      - name: dividends_paid
        description: Dividends paid
      - name: stockholders_equity
        description: Stockholders' equity
      - name: total_assets
        description: Total assets
      - name: accounts_receivable
        description: Accounts receivable
      - name: cash_and_cash_equivalents
        description: Cash and cash equivalents
      - name: current_assets
        description: Current assets
      - name: current_liabilities
        description: Current liabilities
      - name: inventory
        description: Inventory
      - name: long_term_debt
        description: Long-term debt
      - name: revenue_growth
        description: Revenue growth rate


  - name: int_combined_financial_filings
    description: "Combined financial filings from FMP and Yahoo sources"
    columns:
      - name: filing_id
        description: "Unique identifier for the financial filing"
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol of the company"
        data_tests:
          - not_null
      - name: end_of_period
        description: "End date of the financial period"
        data_tests:
          - not_null
      - name: total_revenue
        description: "Total revenue for the period"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: net_income
        description: "Net income (potentially negative)"
      - name: cost_of_goods_sold
        description: "Cost of goods sold (positive, potentially null)"
      - name: selling_general_and_administration 
        description: "Selling, general, and administrative expenses (positive, potentially null)"
      - name: free_cash_flow
        description: "Free cash flow for the period"
        data_tests:
          - not_null
      - name: dividends_paid
        description: "Dividends paid (negative, potentially null)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "<= 0"
              config:
                where: "dividends_paid is not null"
      - name: stockholders_equity
        description: "Total stockholders' equity"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              config:
                where: "stockholders_equity is not null"
      - name: total_assets
        description: "Total assets of the company"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: accounts_receivable
        description: "Accounts receivable balance (positive, potentially null)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              config:
                where: "accounts_receivable is not null"
      - name: cash_and_cash_equivalents
        description: "Cash and cash equivalents balance (positive)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              config:
                where: "cash_and_cash_equivalents is not null"
      - name: current_assets
        description: "Total current assets (positive, potentially null)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              config:
                where: "current_assets is not null"
      - name: current_liabilities
        description: "Total current liabilities (positive, potentially null)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              config:
                where: "current_liabilities is not null"
      - name: inventory
        description: "Inventory balance (positive, potentially null)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              config:
                where: "inventory is not null"
      - name: long_term_debt
        description: "Long-term debt balance (positive, potentially null)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: revenue_growth
        description: "Revenue growth rate"
      - name: shares_growth
        description: "Growth of company shares"
