version: 2

models:
  - name: stg_fmp_api_available_non_us_stocks
    description: "List of available non-US stocks on FMP API (but not on the free plan)"
    columns:
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
  - name: stg_fmp_api_available_us_stocks
    description: "List of available US stocks on FMP API"
    columns:
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
  - name: stg_fmp_balance_sheets
    columns:
      - name: id
        description: "Unique identifier for the balance sheet entry"
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
      - name: stockholders_equity
        description: "Total stockholders' equity"
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: total_assets
        description: "Total assets of the company"
        data_tests:
          - not_null
      - name: accounts_receivable
        description: "Accounts receivable balance"
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: cash_and_cash_equivalents
        description: "Cash and cash equivalents balance"
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: current_assets
        description: "Total current assets"
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: current_liabilities
        description: "Total current liabilities"
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: inventory
        description: "Inventory balance"
        data_tests:
          - not_null
      - name: long_term_debt
        description: "Long-term debt balance"
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: end_of_period
        description: "End date of the reporting period"
        data_tests:
          - not_null
  - name: stg_fmp_quotes
    columns:
      - name: id
        description: "Unique identifier for the quote entry"
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
      - name: request_timestamp
        description: "Timestamp of data request"
        data_tests:
          - not_null
      - name: shares_outstanding
        description: "Number of outstanding shares"
        data_tests:
          - not_null
      - name: earnings_per_share
        description: "Earnings per share"
        # no data tests because we can calculate this from other data as well
      - name: price_earnings_ratio
        description: "Price to earnings ratio"
        # no data tests because for zero earnings the ratio is not defined

  - name: stg_fmp_cashflows
    columns:
      - name: id
        description: "Unique identifier for the cash flow entry"
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
      - name: free_cash_flow
        description: "Free cash flow amount"
      - name: dividends_paid
        description: "Dividends paid"
        data_tests:
          - not_null
      - name: end_of_period
        description: "End date of the reporting period"
        data_tests:
          - not_null

  - name: stg_fmp_profiles
    columns:
      - name: id
        description: "Unique identifier for the company profile"
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
      - name: company_name
        description: "Name of the company"
        data_tests:
          - not_null
      - name: sector
        description: "Sector of the company"
        data_tests:
          - not_null
      - name: industry
        description: "Industry of the company"
        data_tests:
          - not_null
      - name: country
        description: "Home country of the company"
        data_tests:
          - not_null
      - name: current_price
        description: "Current stock price"
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: market_cap
        description: "Market capitalization of the company"
        data_tests:
          - not_null
      - name: request_timestamp
        description: "Timestamp of data request"
        data_tests:
          - not_null

  - name: stg_fmp_income_stmts
    columns:
      - name: id
        description: "Unique identifier for the income statement entry"
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
      - name: total_revenue
        description: "Total revenue for the period"
      - name: net_income
        description: "Net income for the period"
      - name: cost_of_goods_sold
        description: "Cost of goods sold"
      - name: selling_general_and_administration
        description: "Selling, general, and administrative expenses"
      - name: end_of_period
        description: "End date of the reporting period"
        data_tests:
          - not_null

  - name: stg_fmp_financial_growths
    columns:
      - name: id
        description: "Unique identifier for the financial growth entry"
        data_tests:
          - unique
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        data_tests:
          - not_null
      - name: request_timestamp
        description: "Timestamp of data request"
        data_tests:
          - not_null
      - name: revenue_growth
        description: "Year-over-year revenue growth rate"
        data_tests:
          - not_null